eegsynth/eegsynth

module/accelerometer/README.md, module/accelerometer/accelerometer.ini, module/accelerometer/accelerometer.py, module/accelerometer/accelerometer.sh
=> ENH - implemented accelerometer module

README.md, module/playback/README.md, module/playback/playback.ini, module/playback/playback.py, module/playback/playback.sh
it reads from an EDF file (for example those from Nathalie at http://dreamsessions.org) and writes the data as if it were real-time recorded.
=> implemented playback module

lib/EEGsynth.py, module/accelerometer/accelerometer.ini, module/accelerometer/accelerometer.py, module/brain/brain.ini, module/brain/brain.py, module/buffer/buffer.ini, module/eyeblink/eyeblink.ini, module/eyeblink/eyeblink.py, module/heartrate/heartrate.ini, module/heartrate/heartrate.py, module/inputosc/inputosc.ini, module/inputosc/inputosc.py, module/keyboard/keyboard.ini, module/keyboard/keyboard.py, module/launchcontrol/launchcontrol.ini, module/muscle/muscle.ini, module/muscle/muscle.py, module/outputosc/outputosc.ini, module/postprocessing/postprocessing.ini, module/preprocessing/preprocessing.ini, module/redis/redis.ini, module/synchronization/synchronization.ini, module/synchronization/synchronization.py
=> Cleanup ini

.gitignore, bin/install.sh, interface/views/index.jade, lib/shini.LICENSE, lib/shini.README, lib/shini.sh, module/jaga2ft/README.md, module/jaga2ft/jaga2ft.ini, module/jaga2ft/jaga2ft.sh
I was not able to get the original ini_parser to work, so I added another one. Furthermore, I made the code explicit for the raspberry pi version 1, 2 and 3.
=> added jaga2ft module for Jinga-Hi JAGA16 WiFi EEG system

lib/EEGsynth.py
=> Correct minor bug

module/cogito/README.md, module/cogito/cogito.ini, module/cogito/cogito.py, module/cogito/cogito.sh
Worked on 2017-08-05 but still need some compatibility adjustment with package managers.
=> Real-time version of the Cogito module

.gitignore, module/cogito/cogito.py, module/launchcontrol/README.md, module/record/record.ini
These are the changes we made during the last test run in Dwingeloo
=> merge recent changes from the hifipi

module/accelerometer/accelerometer.ini, module/accelerometer/accelerometer.py, module/brain/brain.ini, module/brain/brain.py, module/cogito/cogito.ini, module/cogito/cogito.py, module/eyeblink/eyeblink.ini, module/eyeblink/eyeblink.py, module/heartrate/heartrate.ini, module/heartrate/heartrate.py, module/muscle/muscle.ini, module/muscle/muscle.py, module/preprocessing/preprocessing.ini, module/preprocessing/preprocessing.py, module/record/record.ini, module/record/record.py
=> catch timeout and reset of incoming data

doc/installation-osx.md, module/plotcontrol/README.md, module/plotcontrol/plotcontrol.ini, module/plotcontrol/plotcontrol.py, module/plotsignal/plotsignal.ini, module/plotsignal/plotsignal.py
and some other small improvements
This fixes PR #118
=> implementation to plotcontrol

README.md, module/launchcontrol/launchcontrol.ini, module/launchcontrol/launchcontrol.py, module/normalizecontrol/README.md, module/normalizecontrol/normalizecontrol.ini, module/normalizecontrol/normalizecontrol.py, module/plotcontrol/plotcontrol.ini, module/plotcontrol/plotcontrol.py, module/plotsignal/plotsignal.ini, module/plotsignal/plotsignal.py, module/spectral/spectral.ini, module/spectral/spectral.py
that Stephen made in PR #132. Note that many changes do not deal with the title of that PR (changes in plotting, but are all over the place
I reverted the change to the spectral module (see #136).
I will deal with the change to scaling in launchcontrol in another manner (#134).
=> merge changes 

module/endorphines/endorphines.ini, module/endorphines/endorphines.py, module/inputmidi/inputmidi.ini, module/inputmidi/inputmidi.py, module/inputosc/inputosc.ini, module/inputosc/inputosc.py, module/keyboard/keyboard.ini, module/outputartnet/outputartnet.py, module/outputcvgate/outputcvgate.py, module/outputdmx512/outputdmx512.py
ensure that Redis is between 0-1 and that output to specific devices is limited to the appropriate values (e.g. 0-127 for MIDI)
=> More updates related to scaling

module/keyboard/keyboard.ini, module/keyboard/keyboard.py, module/volcabass/volcabass.ini, module/volcabass/volcabass.py, module/volcabeats/volcabeats.ini, module/volcabeats/volcabeats.py, module/volcakeys/volcakeys.ini, module/volcakeys/volcakeys.py
For the keyboard this had to be done both ways. 
I have tested it with the Yamaha keyboard and with the Volca hardware that I have at home.
=> updated volca and keyboard modules to include mapping between Redis and MIDI 

module/generatecontrol/generatecontrol.ini, module/generatecontrol/generatecontrol.py, module/generatesignal/generatesignal.ini, module/generatesignal/generatesignal.py
ensure that all Redis values are properly scaled
use constant phase increase to avoid jumps when changing the frequency
added dutycycle option for square wave
=> revised generate signal and generatecontrol 

module/keyboard/keyboard.py, module/quantizer/quantizer.ini, module/sequencer/sequencer.ini, module/sequencer/sequencer.py, module/synthesizer/synthesizer.ini, module/synthesizer/synthesizer.py
=> improve output scaling for sequencer module

module/endorphines/endorphines.py
See also @stephenwhitmarsh comment on PR #189
=> do not delete the config object, it is needed later on. 

module/launchcontrol/launchcontrol.ini, module/launchcontrol/launchcontrol.py, module/launchpad/launchpad.ini, module/launchpad/launchpad.py
- updated the ini files
- added control scale and offset for launchpad (which was missing, i.e. a bug)
- made the code more consistent between the two modules
=> FIX #195 - implemented new slap button mode

module/quantizer/quantizer.py, module/synchronization/README.md, module/synchronization/synchronization.ini, module/synchronization/synchronization.py
=> improve synchronization module

module/synchronization/README.md, module/synchronization/synchronization.ini, module/synchronization/synchronization.py
which synchronizes the Redis, MIDI and Serial threads. I also implemented variable steps and adjust values to align the Redis+Serial with the MIDI.
I have done extensive testing of MIDI and serial cv/gate output (using multiple volca's). I have not tested redis to great extent, but that code is very simple.
=> improved the synchronization by using a single clock thread

module/plotfreq/plotfreq.py, module/postprocessing/postprocessing.py
Because it otherwise fail with empty keys, as e.g. when starting up.
My mistake: still had previous commit added.
=> added try-catch around eval

patches/iklectik/linux/endorphines.ini, patches/iklectik/linux/historycontrol.ini, patches/iklectik/linux/keyboard.ini, patches/iklectik/linux/launchcontrol.ini, patches/iklectik/linux/openbci2ft.ini, patches/iklectik/linux/outputosc.ini, patches/iklectik/linux/patch.sh, patches/iklectik/linux/playbackcontrol.ini, patches/iklectik/linux/playbacksignal.ini, patches/iklectik/linux/plotcontrol.ini, patches/iklectik/linux/plotsignal.ini, patches/iklectik/linux/plotspectral.ini, patches/iklectik/linux/postprocessing.ini, patches/iklectik/linux/spectral.ini, patches/iklectik/linux/synchronization.ini
(apologies for not making a separate branch)
=> added iklektik patch

module/bitalino2ft/README.md, module/bitalino2ft/bitalino2ft.ini, module/bitalino2ft/bitalino2ft.py
The initial code only has example code and some documentation. I still have to extend it with 
- reading of the settings from the ini file
- writing of the data to the buffer
=> add support for the bitalino board

lib/EEGsynth.py, module/recordtrigger/README.md, module/recordtrigger/recordtrigger.ini, module/recordtrigger/recordtrigger.py
it reads REDIS messages (to which it is subscribed) and writes them with a millisecond precision timestamp to a TSV file.
=> Implemented recordtrigger module

module/plotcontrol/plotcontrol.py, module/plotsignal/plotsignal.py, module/plotspectral/plotspectral.py
=> added CONTROL-C handling in modules using pyqt #239

lib/EEGsynth.py, module/generateclock/generateclock.ini, module/generateclock/generateclock.py, module/heartrate/heartrate.py, module/outputmidi/outputmidi.ini, module/outputmidi/outputmidi.py, module/plottrigger/plottrigger.ini, module/plottrigger/plottrigger.py, module/sequencer/sequencer.ini, module/sequencer/sequencer.py
=> re-implemented sequencer module with external clock

lib/EEGsynth.py, module/calibration/calibration.py, module/historycontrol/historycontrol.ini, module/historycontrol/historycontrol.py, module/inputosc/inputosc.py, module/launchcontrol/launchcontrol.py, module/launchpad/launchpad.py, module/plotsignal/plotsignal.py, module/plotspectral/plotspectral.py
for patch.getstring, getfloat and getint
This fixes #265
=> make more consistently use of the multiple=True option 

lib/EEGsynth.py, module/accelerometer/accelerometer.py, module/calibration/calibration.py, module/clockdivider/clockdivider.py, module/clockmultiplier/clockmultiplier.py, module/generateclock/generateclock.py, module/generatecontrol/generatecontrol.py, module/geomixer/geomixer.py, module/heartrate/heartrate.py, module/historycontrol/historycontrol.py, module/inputmidi/inputmidi.ini, module/inputmidi/inputmidi.py, module/inputosc/inputosc.py, module/keyboard/keyboard.py, module/launchcontrol/launchcontrol.ini, module/launchcontrol/launchcontrol.py, module/launchpad/launchpad.ini, module/launchpad/launchpad.py, module/plotspectral/plotspectral.py, module/postprocessing/postprocessing.py, module/quantizer/quantizer.py, module/recordcontrol/recordcontrol.py, module/recordsignal/recordsignal.py, module/rms/rms.py, module/sequencer/sequencer.py, module/spectral/spectral.py
prior to merging this requires a code review and more exhaustive testing. I have already tested with a number of test patches, but not with proper ExG attached.
=> FIX #271 - send triggers and control values more consistently

module/generateclock/README.md, module/generateclock/generateclock.ini, module/generateclock/generateclock.py
=> allow generateclock to also start/stop the sequencer

doc/openbci.md, hardware/headband/README.md, module/generatesignal/generatesignal.ini, module/geomixer/geomixer.ini, module/geomixer/geomixer.py, module/outputcvgate/outputcvgate.py, module/plotspectral/plotspectral.ini, module/postprocessing/postprocessing.py, module/preprocessing/preprocessing.py, module/spectral/spectral.py, patches/iklectik/linux/openbci2ft.ini, patches/iklectik/raspberrypi/openbci2ft.ini
These are mostly changes to documentation, example ini files, etc.
There are also some small fixes to some modules and a significant change to the geomixer module.
=> (mostly) documentation changes while preparing gothenburg patch

README.md, doc/README.md, doc/avmixer.md, doc/buffer.md, doc/contribute.md, doc/design.md, doc/history.md, doc/inifile.md, doc/input.md, doc/manual_control.md, doc/midi.md, doc/module-overview.md, doc/output.md, doc/patching.md, doc/preface.md, doc/scripts.md, doc/tutorial1.md, doc/tutorial2.md, module/generateclock/generateclock.py, module/generatecontrol/generatecontrol.py
@robertoostenveld - yeah! this is the last edits for this run. Looking forward hearing what you think, and starting to ironing the sections out. Hope you like it!
=> Onthetrainback

module/outputaudio/outputaudio.py
this allows the input (for example EEG) to be upsampled to the output audio. Note that this does not deal with aliasing effects, and upon testing fails when the difference in sampling rates is too large. There are some artefacts in the output due to the block-wise processing of the audio buffer (1024 blocks for 44100 Hz audio), these become more apparent when the FT buffer sampling rate is lower.
=> implemented support for variable sampling rates between input and output

module/postprocessing/postprocessing.ini, module/postprocessing/postprocessing.py, module/processtrigger/processtrigger.ini, module/processtrigger/processtrigger.py, module/sampler/README.md, module/sampler/sampler.ini, module/sampler/sampler.py
It allows playback of samples from wav files. Each sample is triggered by a pubsub trigger message
=> Implemented sampler module

module/spectral/spectral.ini, module/spectral/spectral.py
Easier than expected! See issue #347
=> added redis-controlled window-size for spectral estimate, see #347

module/playbacksignal/playbacksignal.py
I added a few missing global variables which caused playbacksignal to crash, and modified the try/except statements so it is specific to SystemExit, KeyboardInterrupt and RuntimeError.
=> Solving #372

module/delaytrigger/README.md, module/delaytrigger/__init__.py, module/delaytrigger/delaytrigger.ini, module/delaytrigger/delaytrigger.py
=> Add delaytrigger module #394

doc/installation-windows.md
=> add rt-midi installation

lib/EEGsynth.py, module/complexity/complexity.py, module/inputcontrol/inputcontrol.py, module/plotcontrol/plotcontrol.py, module/plotimage/plotimage.py, module/plotsignal/plotsignal.py, module/plotspectral/plotspectral.ini, module/plotspectral/plotspectral.py, module/plottopo/plottopo.py, module/plottrigger/plottrigger.py, module/preprocessing/preprocessing.py, module/spectral/spectral.ini, module/spectral/spectral.py, module/vumeter/vumeter.py
These are a number of changes to make my Unicorn test patch behave a bit better. I propose that the actual test patch goes to a repository on the BBDMI gitlab server.
=> Unicorn test

doc/openbci.md
Think you mean Processing here, when referring to the JVM-based language for working with signals. :)
=> s|Programming|Processing|g

module/inputcontrol/inputcontrol.ini, module/videoprocessing/README.md, module/videoprocessing/__init__.py, module/videoprocessing/videoprocessing.ini, module/videoprocessing/videoprocessing.py
This is based on an [OpenCV](https://opencv.org) implementation that I already started in 2019. I now finished it, as Per will probably use it for a performance in Ghent, Belgium.
=> Implement videoprocessing module
